### ISSUE TITLE
Create anonymised versions of input spreadsheets

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#37]
Suggest doing this last, since easier to develop against the non-anonymised versions

**Comment by masonlr** [comment]
>  sufficiently "anonymized"

This is probably as anonymised as we can get here. 

I was thinking about encrypting the input files, but the inherent problem with python is that we're distributing the challenge source code, rather than a compiled binary (which we'd be doing in other compiled languages). Encryption is not really useful here because we are distributing the python codebase. If they have the code, a challenge participant could always add in new debug statements and get the raw content of the pycel format.

I was thinking about scenarios where you fetch a remote secret and then decrypt the inputs:

```
encrypted_input_file + SECRET = input_file
```

but I can't see the point of this given the limitations when distributing python codebases.

**Comment by moriartyjm** [comment]
Thanks guys. How about the following simple approach:
* Create a copy of 'Pathways to Net Zero - Simplified.xlsx'
* Delete all cells containing text labels
* Save this as 'Pathways_unlabelled.xlsx'
* Use 'Pathways_unlabelled.xlsx' as the input spreadsheet in the `env`

This way, the labels do not exist -- so cannot appear in the .pkl or .yml files.

The drawback is that 'Pathways_unlabelled.xlsx' is less human readable. But if we maintain a parallel labelled copy in Teams, this should not be a problem.
